### ISSUE TITLE
A question about the code

### ISSUE THREAD

**Issue by snowball521** [xyq7/GradSafe#3]
Thank you for your wonderful work.  I’m currently working to reproduce your code and noticed that the input ends with “sorry” when calculating the gradient. I’m a bit confused about why this particular token is required in input. Thank you so much.

**Comment by snowball521** [comment]
I apologize for the confusion earlier. After reviewing your code more carefully,  I realized that I made a stupid mistake. I am so sorry.

**Comment by xyq7** [comment]
No worry. Please feel free to reach out if there is any question!
